# Generated by Django 4.1.5 on 2024-01-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stu_register",
            name="mobile",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="stu_register",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
