# Generated by Django 4.1.5 on 2024-02-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_exam_result_tab_strike_exam_result_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart", models.CharField(max_length=15)),
                ("question1", models.TextField()),
                ("question2", models.TextField()),
                ("question3", models.TextField()),
                ("quest1_option", models.TextField()),
                ("quest2_option", models.TextField()),
                ("quest3_option", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="stu_register",
            name="department",
            field=models.CharField(
                choices=[("computer", "Computer"), ("biology", "Biology")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stu_register",
            name="reg_type",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exam_result",
            name="result",
            field=models.CharField(default="Pass", max_length=5),
        ),
    ]
