# Generated by Django 4.1.5 on 2024-02-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_questions_stu_register_department_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="questions",
        ),
    ]
