# Generated by Django 4.1.5 on 2024-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_delete_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart", models.CharField(max_length=15)),
                ("question1", models.TextField()),
                ("question2", models.TextField()),
                ("question3", models.TextField()),
                ("quest1_option1", models.TextField()),
                ("quest1_option2", models.TextField()),
                ("quest1_option3", models.TextField()),
                ("quest1_option4", models.TextField()),
                ("quest2_option1", models.TextField()),
                ("quest2_option2", models.TextField()),
                ("quest2_option3", models.TextField()),
                ("quest2_option4", models.TextField()),
                ("quest3_option1", models.TextField()),
                ("quest3_option2", models.TextField()),
                ("quest3_option3", models.TextField()),
                ("quest3_option4", models.TextField()),
            ],
        ),
    ]
